CREATE TABLE tb_player (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(1024) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE tb_game (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(1024) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT,
    PRIMARY KEY (id)
);

ALTER TABLE tb_game 
ADD CONSTRAINT fk_created_by 
FOREIGN KEY (created_by) REFERENCES tb_player(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

